[tool.poetry]
name = "rasa-learning"
version = "0.1.0"
description = "dependencies"
authors = ["kukretinishtha"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
rasa = "^3.6.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
